### PR TITLE
Update dns.md

### PR DESCRIPTION
**Pull request by travissalascox**
This should fix a broken link referenced in [#1640](https://github.com/kubernetes/kubernetes.github.io/issues/1640). Looks like a lot of information was taken out of [this](https://github.com/kubernetes/kubernetes/tree/master/build-tools/kube-dns) README.md [recently](https://github.com/kubernetes/kubernetes/commit/85dcdccb2f0ca7d74c74393047144ec108e751a8), if you'd like i can delete the reference section completely if it is out of date and/or no longer needed.

---
This change is [Reviewable](https://reviewable.kubernetes.io/reviews/kubernetes/kubernetes.github.io/1642)

### CODE REVIEW

**Comment by travissalascox** [comment]
I signed it!

**Comment by travissalascox** [comment]
Also, signed the other CLA for the Linux Foundation. Not sure how to kick off the check for that one again though.

**Comment by travissalascox** [comment]
@davidopp looks you were auto assigned to the PR. had a quick question, first time trying contributing to any project in this org and not really sure how you all do things. Looks like the TravisCI build is failing, but don't think it has anything to do with my PR (at least as far as i can tell).

**From TravisCI**
```
# k8s.io/kubernetes.github.io/test_test

test/examples_test.go:130: undefined: batch.ScheduledJob

test/examples_test.go:131: t.Namespace undefined (type runtime.Object has no field or method Namespace)

test/examples_test.go:132: t.Namespace undefined (type runtime.Object has no field or method Namespace)

test/examples_test.go:134: undefined: "k8s.io/kubernetes/pkg/apis/batch/validation".ValidateScheduledJob

test/examples_test.go:245: undefined: batch.ScheduledJob

FAIL	k8s.io/kubernetes.github.io/test [build failed]

The command "go test -v k8s.io/kubernetes.github.io/test" exited with 2.

0.08s$ $GOPATH/bin/md-check --root-dir=$HOME/gopath/src/k8s.io/kubernetes.github.io

----------------

-- ✔ Success! --

----------------
```

 Is there anything that i need to do to resolve that?

**Comment by travissalascox** [comment]
@davidopp i see you closed and reopened this PR a day ago. guessing it was to kick off the travisCI build again? I'm pretty sure this PR isn't what is causing the build failure since #1672 seems to have the same problem. Just wondering, is there anything that i can do to help with the build failure if someone isn't already working on it, or should i just hold tight?

**Comment by travissalascox** [comment]
hi @jaredbhatti, not trying to make waves or anything, but have had this PR opened for a few days now. Saw that you were the most recent person to merge a PR in. Was wondering if you could please review this PR for me. have never contributed to this organization before and not to sure what else i need to do for this PR, and even just a little guidance would be greatly appreciated! :smile_cat:

**Comment by davidopp** [comment]
@devin-donnelly
